/// <reference types="jquery" />
export * from "./src/utils/modern"
export * from "./src/synth/customNodes"
export * from "./src/synth/notes"
export * from "./src/synth/palette"
export * from "./src/utils/file"
export * from "./src/synth/synth"
export * from "./src/synth/instrument"
export * from "./src/synth/timer"
